imports:
    - { resource: datasource.yml }

modules:
    active_modules:
    - Framework
    - Application
    - PPI\BowerModule
    - PPI\SmartyModule
    - PPI\TwigModule
    - PPI\TwitterBootstrapModule
    module_listener_options:
        config_cache_enabled: false
        module_map_cache_enabled: false
        cache_dir: "%app.cache_dir%"
        config_cache_key: %app.name%
        module_paths: ['./modules', './vendor']

framework:
    templating:
        engines: ["php"]

    skeleton_module:
        path: './utils/skeleton_module'