# app/config/base/symfony_routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

TestBundle:
    resource: "@TestBundle/Resources/config/routing.yml"

#
#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

